/**
 * Error Codes Constants
 * Standardized error codes across the application
 */

export const ERROR_CODES = {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // User errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_EMAIL_TAKEN: "USER_EMAIL_TAKEN",

  // Event errors
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_EXPIRED: "EVENT_EXPIRED",
  EVENT_INVALID_TOKEN: "EVENT_INVALID_TOKEN",
  EVENT_FORBIDDEN: "EVENT_FORBIDDEN",

  // Photo errors
  PHOTO_NOT_FOUND: "PHOTO_NOT_FOUND",
  PHOTO_UPLOAD_FAILED: "PHOTO_UPLOAD_FAILED",
  PHOTO_TOO_LARGE: "PHOTO_TOO_LARGE",
  PHOTO_INVALID_TYPE: "PHOTO_INVALID_TYPE",

  // Guest errors
  GUEST_SESSION_EXPIRED: "GUEST_SESSION_EXPIRED",
  GUEST_SESSION_INVALID: "GUEST_SESSION_INVALID",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // Rate limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Server errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
