import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#fbf8ff",
        "on-tertiary": "#6a0a31",
        "on-background": "#f8f5fd",
        "primary-dim": "#8a4cfc",
        "secondary-container": "#612b8f",
        "on-primary-fixed": "#000000",
        "surface-variant": "#25252c",
        "primary-fixed": "#b28cff",
        "error-dim": "#d73357",
        "surface-dim": "#0e0e13",
        outline: "#76747b",
        surface: "#0e0e13",
        "tertiary-container": "#fe81a4",
        "on-tertiary-container": "#5a0027",
        "error-container": "#a70138",
        "on-secondary-container": "#e5c4ff",
        "surface-bright": "#2b2b33",
        primary: "#bd9dff",
        "tertiary-fixed": "#ff8eac",
        "on-surface-variant": "#acaab1",
        "secondary-dim": "#be86ef",
        "surface-container-lowest": "#000000",
        "on-primary-container": "#2e006c",
        "on-tertiary-fixed-variant": "#711036",
        "primary-fixed-dim": "#a67aff",
        "on-secondary": "#3b0065",
        "on-surface": "#f8f5fd",
        background: "#0e0e13",
        tertiary: "#ff97b2",
        "secondary-fixed": "#e6c5ff",
        "inverse-primary": "#742fe5",
        "on-secondary-fixed-variant": "#6b369a",
        secondary: "#c38bf5",
        error: "#ff6e84",
        "surface-container": "#19191f",
        "inverse-on-surface": "#55545a",
        "secondary-fixed-dim": "#ddb3ff",
        "surface-container-highest": "#25252c",
        "surface-tint": "#bd9dff",
        "on-secondary-fixed": "#4d137b",
        "on-primary-fixed-variant": "#390083",
        "on-error-container": "#ffb2b9",
        "on-error": "#490013",
        "primary-container": "#b28cff",
        "surface-container-low": "#131318",
        "surface-container-high": "#1f1f26",
        "on-tertiary-fixed": "#380016",
        "outline-variant": "#48474d",
        "tertiary-fixed-dim": "#f77c9e",
        "on-primary": "#3c0089",
        "tertiary-dim": "#f17799",
      },
      fontFamily: {
        headline: ["var(--font-jakarta)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-down": "slideDown 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
